;;; golden-ratio-scroll-screen-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from golden-ratio-scroll-screen.el

(autoload 'golden-ratio-scroll-screen-up "golden-ratio-scroll-screen" "\
scroll half screen up

(fn &optional ARG)" t)
(autoload 'golden-ratio-scroll-screen-down "golden-ratio-scroll-screen" "\
scroll half screen down

(fn &optional ARG)" t)
(register-definition-prefixes "golden-ratio-scroll-screen" '("golden-ratio-scroll-"))

;;; End of scraped data

(provide 'golden-ratio-scroll-screen-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; golden-ratio-scroll-screen-autoloads.el ends here
